[2021-11-21 12:05:34,900] {processor.py:163} INFO - Started process (PID=74068) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:05:34,900] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-21 12:05:34,901] {logging_mixin.py:109} INFO - [2021-11-21 12:05:34,901] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:05:34,973] {logging_mixin.py:109} INFO - [2021-11-21 12:05:34,965] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-21 12:05:35,080] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:05:35,097] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.200 seconds
[2021-11-21 12:09:17,224] {processor.py:163} INFO - Started process (PID=76105) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:09:17,225] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-21 12:09:17,226] {logging_mixin.py:109} INFO - [2021-11-21 12:09:17,226] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:09:17,267] {logging_mixin.py:109} INFO - [2021-11-21 12:09:17,264] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-21 12:09:17,338] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:09:17,352] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.129 seconds
[2021-11-21 12:11:50,994] {processor.py:163} INFO - Started process (PID=77809) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:11:50,994] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-21 12:11:50,995] {logging_mixin.py:109} INFO - [2021-11-21 12:11:50,995] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:11:51,031] {logging_mixin.py:109} INFO - [2021-11-21 12:11:51,028] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-21 12:11:51,226] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-21 12:11:51,262] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.269 seconds
